version: "3.8"

services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      /usr/local/bin/goose -dir migrations postgres
      "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" up
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
